[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.3", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
iced = { version = "0.10", features = ["debug", "tokio"] }
serde_json = "1.0"
chrono = "0.4"