apiVersion: v1
kind: Service
metadata:
  name: engine-service
spec:
  selector:
    app: engine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP  # The default type